### ISSUE TITLE
Microservices

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/generator-feathers-plus#128]
Beau Shaw [10:10 PM]
Does anyone have any advice for how to structure services as micro-services within the same app? Basically micro-services within the same monolith. Feathers is unique in that services can be called internally and externally.
I have created an app in feathers that had two clients, an admin app and a native app. I was able to handle the different needs (specifically validation and permissions) within each service’s hooks. But I am currently working on an app that has at least 4 client apps, each with very different validation/permission/authentication needs. As clean as hooks are, that will get messy IMO. This seems like an exact use-case for micro-services. But, I don’t necessarily want to break my server into what would basically be 5 servers/repos/etc and all of the overhead that comes with that. I am not concerned about scaling up/down the micro-services independently just yet; I want to keep them in the same “monolith”, but somehow “layer” them similar to how real micro-services work. Feathers is ideally suited for this (Props to all of the creators and maintainers! Feathers is dope…)
Anybody got any links or a repo they would be willing to share that accomplishes this?

daffl [10:15 PM]
I’m thinking you could write a “core” app that provides the common services (and possibly hooks). Then create another app for each use-case that does something like

```const coreApp = require('./core');
const app = feathers();

app.configure(authentication()); // etc
app.use('/users', coreApp.service('users'));

app.service('/users').hooks({
  before: app1BeforeHooks
  // etc
});```
(edited)
You can re-use the services from one app in another. At the top level it will create an identical copy of the service so it shouldn’t interfere with the `coreApp` services.

**Comment by eddyystop** [comment]
https://moleculer.services/
https://moleculer.services/docs/0.13/
https://github.com/moleculerjs/moleculer

https://github.com/zygos/moleculer-adapter-feathers#readme

**Comment by eddyystop** [comment]
"Basically, the plugin would add a service that stores dehydrated feathers-plus spec files (by dehydrated I mean spec files that includes custom code), then, as needed, generate the application from the spec, compress the application using @zeit/ncc, package the application as a binary using @zeit/pkg, launch a new application instance in a child process/container, launch a new proxy for the application instance, and add the application instance to the application manifest."

Well, that's eye brow raising. I never considered using feathers-gen*.* + custom modules as a way of distributing an application.

@daffl needs to get involved in this.

**Comment by lukeburpee** [comment]
And as a side note, I started working on this the other day because pm2's AGPL is lame.

**Comment by 3kynox** [comment]
@lukeburpee Would you agree to share your experience with zeit/pkg especially?

I'm trying to package a feathers-plus app with another node application that feathers run/stop.

Thanks anyway.

**Comment by lukeburpee** [comment]
@3kynox What exactly are you trying to do? @zeit/pkg can be a little tricky for feathers-plus because pkg has trouble with dynamic imports, particularly the dynamic imports used by the config package. Additionally, if your application requires additional native node modules, pkg will not include them.

Either way, to get a basic feathers-plus app running with pkg, you have to include a "requires.js" or some other such file, that imports the config package directly from node_modules

i.e.`require('./node_modules/config');`

Then include the file in the pkg config within your package.json file

`  "bin": {
    "tester": "compiled/index.js"
  },
  "pkg": {
    "scripts": [
      "compiled/**/**/*.js",
      "require.js"
    ]
`

This doesn't account for any native node modules you might want to include separately.

Rather than using @zeit/pkg, I've been using **[nexe](https://github.com/nexe/nexe)** to compile code into binaries, which supports native node modules via fusebox. It may require you to build node for your particular platform if there isn't a pre-existing nexe binary (had to compile mine for mac-x64-11.3.0), but it does this for you from the nexe command with the `--build` flag. If you're using typescript code, make sure to point your main file path in your package.json to your compiled ts code dist/index.js rather than your src/index.ts. Nexe says it can compile typescript code directly, but, if you point to your src/index.ts, you'll get import errors because the binary can't find the other source files.

Let me know if you need anything else.

**Comment by lukeburpee** [comment]
@3kynox I've created a pull request that uses a script to package the feathers-plus application in a binary. In the meantime, one additional note is that you need to use the nexe@next version of nexe for everything to work properly.

**Comment by 3kynox** [comment]
Thanks a lot for your reply and all of your sharing here @lukeburpee 

@3kynox What exactly are you trying to do?

- I have a basic feathers-plus app on one side
- I'm calling from feathers-plus another node app using exec which produce stdout (I'm not passing stdout to the client yet). Here is what I use to do so:

```
let spawn = exec.spawn
let myProcess

app.use('/run', {
  find() {
    function getBitRageOutput() {
      myProcess = spawn('node', ['../index.bitrage'], { detached: true })
      myProcess.stdout.setEncoding('utf-8')
      myProcess.stdout.on('data', function (data) {
        // eslint-disable-next-line
        console.log(data)
      })

      return Promise.resolve(myProcess)
    }

    return getBitRageOutput()
  }
})

app.use('/stop', {
  find() {
    function killBitRage() {
      return process.kill(-myProcess.pid)
    }

    return Promise.resolve(killBitRage())
  }
})
```
- the external node app is already built when releasing using zeit/pkg.

What I need to achieve is to include my feathers-plus app... or the inverse (configure pkg with my feathers-plus app then include my external app and make it callable).

I could give a try to nexe but I found out that it doesn't support yet arm architectures.

Thanks again for your great input.

**Comment by lukeburpee** [comment]
Is there a reason you're running the child process with the "detached" option? In detached mode, the child has its own console window, so you need to pipe the stout from the child process to the parent process. So, 

`myProcess.stdout.pipe(process.stdout)` 

You may want to check out [execa](https://github.com/sindresorhus/execa) for running your child processes and [fkill](https://github.com/sindresorhus/fkill) for stopping the process. Makes things a lot easier when dealing with process promises. 

Personally, I'm using a custom event emitter on the parent app to pipe my child process stdout. Something like,

```
app.on('process:output', function (data) {
  // send data anywhere you want
});

app.use('/run', {
  find() {
    function getBitRageOutput() {
      myProcess = spawn('node', ['../index.bitrage'], { detached: true })

      myProcess.stdout.setEncoding('utf-8')

      myProcess.stdout.on('data', app.emit('process:output', {
        pid: myProcess.pid,
        output: data,
        /* any additional metadata you want to include */
      })

      return Promise.resolve(myProcess)
    }

    return getBitRageOutput()
  }
})
```

If you need additional ideas, my [feathers-service-manager](https://github.com/lukeburpee/feathers-service-manager) repo contains an extendable service class for running child processes in the "core-services" package. It's unpublished/unmaintained, but the package has a few useful bits.

P.S. I checked the documentation/issues for nexe and you should be able to run it on arm, but you have to build the binary on the raspberry pi/arm device.

P.P.S. It may be better to continue this conversation on the feathers slack channel in order to keep this issue on topic.

**Comment by 3kynox** [comment]
Yes true, thanks for your great inputs :)
