### ISSUE TITLE
Help sought with TypeScript issues

### ISSUE THREAD

**Issue by eddyystop** [feathers-plus/generator-feathers-plus#130]
You guys did a great job handling the existing TS issues. Complements to all of you.

There are some remaining TS issues. Does anyone have the time and inclination to address some of them?

1. feathers-hooks-common affects the generator. 2 hooks need typings ~https://github.com/feathers-plus/feathers-hooks-common/issues/468~ https://github.com/feathers-plus/feathers-hooks-common/issues/474 ~https://github.com/feathers-plus/feathers-hooks-common/issues/461~

2. Once `generate graphql` generates resolvers, you can run `generate service/all` to create a serviceName.populate.js module for the service. That module uses fgraphql. Marshall has used the js version in the wild and it significantly reduced the complexity of his hooks. I added some obvious code for TS but I doubt an app using that would boot. You can extract test-expands/ts-cumulative-1-nedb.test-copy, run `generate all` on it, and follow up.

I can't really write a followup to the fgraphql article https://blog.feathersjs.com/fgraphql-feathers-graphql-hook-38faee75dd1 until (2) is done.

@lukeburpee  @NickBolles @j2L4e  ^^^

**Comment by j2L4e** [comment]
#461 can be fixed via https://github.com/feathers-plus/feathers-hooks-common/pull/463 for CI, I'll still have to make it work locally though. Could you guys pull it and check if `npm run dtslint` passes?
(2) isn't a lot of work, it'd be great if one wants to do it, otherwise I'll get to it tomorrow.

**Comment by lukeburpee** [comment]
@j2L4e did you mean `npm run lint:types` in your feathers-hooks-common fork? If so, the script installs and the script passes

**Comment by j2L4e** [comment]
exactly. thanks :+1:

**Comment by eddyystop** [comment]
Great job everyone! Much thanks.

cli+ v0.7.72 published using generator v0.6.70

**Comment by j2L4e** [comment]
serviceName.populate.ts isn't done, yet. There's some more work to do

**Comment by eddyystop** [comment]
Welcome back NickBolles. Issue 474 has been handled; I forgot to close the issue.

We still need your changes in https://github.com/feathers-plus/generator-feathers-plus/pull/151 (?) submitted as small PRs so they can be reviewed one by one.

**Comment by NickBolles** [comment]
@eddyystop Thanks! Haha, I basically haven't touched personal development in the last month or so because of work and the Holidays. I'm back at it though. 

I kinda forgot about #151. I'll submit a PR for that and I noticed that there are a few other linting issues, such as line length and brackets. 

That gets into a bigger issue that I'm kicking around, which is just overall formatting based on the user's workspace. [I started writing this out, but I think it belongs in another issue, I'll create one in a minute]

**Comment by eddyystop** [comment]
Its difficult enough generating code. Its more difficult generating JS and TS code together. I'm not sympathetic to making things more convoluted by supporting multiple style guides. (If that's what you mean by workspace.) I suggest people run a linter with a fix option if they really want a particular style.
