### ISSUE TITLE
Unexpected generated schema using sequelize driver : invalid types

### ISSUE THREAD

**Issue by franfran3** [feathers-plus/generator-feathers-plus#162]
### Steps to reproduce

1. I inited the application from scratch:
```
yarn init -y
yarn add @feathers-plus/cli
```
I Added a fake `test:all` script in package.json (see #121 )
```
node ./node_modules/feathers-plus g app
```

2. Generate a service 'test' using Sequelize + MySQL driver and no GraphQL support
3. Define JSON-schema in src/services/test/test.schema.js

```
...
  properties: {
    // !code: schema_properties
    name: {},
    active: {
      type: 'boolean',
      readonly: false,
      default: true,
    }

    // !end
...
```

4. Re-run `feathers-plus g service` on test service

### Expected behavior

Expect the src/services/test/test.sequelize.js to be valid

### Actual behavior

Got many undefined vars in the generated source: TEXT, Constructor, baseType

```
// generated src/services/test/test.sequelize.js
/* eslint quotes: 0 */
// Defines Sequelize model for service `test`. (Can be re-generated.)
const merge = require('lodash.merge');
const Sequelize = require('sequelize');
// eslint-disable-next-line no-unused-vars
const DataTypes = Sequelize.DataTypes;
// !code: imports // !end
// !code: init // !end

let moduleExports = merge({},
  // !<DEFAULT> code: sequelize_model
  { 
    name: { 
      type: function(length) { 
    var options = typeof length === 'object' && length || { 
      length: length
    };
    if (!(this instanceof TEXT)) return new TEXT(options);
    this.options = options;
    this._length = options.length || '';
  } 
    },
    active: { 
      type: function () { 
        if (!(this instanceof Constructor)) { 
          var args = [null].concat(arguments);
          var FactoryFunction = Constructor.bind.apply(Constructor, args);
          return new FactoryFunction();
        } 
        baseType.apply(this, arguments);
      },
      default: true
    } 
  },
  // !end
  // !code: moduleExports // !end
);

// !code: exports // !end
module.exports = moduleExports;

// !code: funcs // !end
// !code: end // !end
```

### System configuration

**Module versions** : (dependencies from packages.json) :
   "@feathers-plus/cli": "^0.7.75",
    "@feathersjs/configuration": "^2.0.6",
    "@feathersjs/errors": "^3.3.6",
    "@feathersjs/express": "^1.3.1",
    "@feathersjs/feathers": "^3.3.1",
    "ajv": "^5.5.2",
    "compression": "^1.7.3",
    "cors": "^2.8.5",
    "cross-env": "^5.2.0",
    "feathers-hooks-common": "^4.20.0",
    "feathers-sequelize": "^3.1.3",
    "helmet": "^3.15.0",
    "lodash.merge": "^4.6.1",
    "mysql2": "^1.6.4",
    "sequelize": "^4.42.0",
    "serve-favicon": "^2.5.0",
    "winston": "^3.1.0"

**NodeJS version**: 10.15.0

**Operating System**: Linux Ubuntu

**Module Loader**: Yarn

**feathers-gen-specs.json:

```
{
  "options": { 
    "ver": "1.0.0",  
    "inspectConflicts": false, 
    "semicolons": true,        
    "freeze": [],              
    "ts": false
  },
  "app": {                     
    "environmentsAllowingSeedData": "",
    "seedData": false,         
    "name": "x",
    "description": "Project x",
    "src": "src",    
    "packager": "yarn@>= 0.18.0",
    "providers": [             
      "rest"                   
    ]
  },
  "services": {
    "test": {
      "name": "test",
      "nameSingular": "test",
      "subFolder": "",
      "fileName": "test",
      "adapter": "sequelize",
      "path": "/test",
      "isAuthEntity": false,
      "graphql": false
    }
  },
  "hooks": {},
  "connections": {
    "sequelize": {
      "database": "mysql",
      "adapter": "sequelize",
      "connectionString": "mysql://localhost/x"
    }
  }
}

```

**Comment by eddyystop** [comment]
Conversion from JSON-schema to a Sequelize model is doen with https://github.com/ronalddddd/sequelizer. That does not support `readonlt`.

I suggest you customize the Sequelize readonly attribute in serviceName.sequelize.?s at the insertion point named `modelExports.

You could also consider creating an issue or submitting a PR to ronalddddd/sequelizer

**Comment by franfran3** [comment]
Ok but event when readonly is removed, the bug occurs. Looks like sequelizeNativeFuncs if lib/generators/writing/index.js is not used for template substitution.

**Comment by eddyystop** [comment]
I realize I missed something when first reading your initial post. You created a package.json before running `generate app`. You cannot do that. The generator will not initialize package.json properly if the file already exists; it assumes its already been initialized.

**Test running the right way**
- I created a new folder on Ubuntu
- Ran generate app with defaults. A package.json was properly created with the default test: all script.
- Ran generate service called test Sequelize + MySQL driver and no GraphQL support
- Added your name and active field (without readonly).
- Ran generate service for test.
- My test/test.sequelize.js contained
```js
let moduleExports = merge({},
  // !<DEFAULT> code: sequelize_model
  {
    name: {
      type: DataTypes.TEXT
    },
    active: {
      type: DataTypes.BOOLEAN,
      default: true
    }
  },
  // !end
  // !code: moduleExports // !end
);
```
- I added readonly to active. The part of test/test.sequelize.js listed above remained unchanged.

**Test running as per OP**
- I created a new folder.
- I added a package.json with a scripts['test.all'] property.
- I ran generate app with defaults
- package.json was malformed as expected. It only had an additional scripts['start:seed'] property.
- I ran generate service for test
- I added the schema properties (without readonly).
- test/test.sequelize.js still contained
```js
let moduleExports = merge({},
  // !<DEFAULT> code: sequelize_model
  {
    name: {
      type: DataTypes.TEXT
    },
    active: {
      type: DataTypes.BOOLEAN,
      default: true
    }
  },
  // !end
  // !code: moduleExports // !end
);
```
- I added readonly property. The part of the module above remained unchanged.

**So I cannot recreate your results running the latest generator on Ubuntu.** Perhaps its because your generator is not installed globally. But someone else ran a local install of it some months ago and did not report any issues. I think he installed in node_modules but I'm not sure. You can dig into the reported issues if you are interested,

**Comment by franfran3** [comment]
Thx for your reply. You are right, when installed locally it works.
The fact is that when installed localy, the generator uses the local sequelize which is at version 4.42.0.
The global installation uses sequelize at version 3.34.0.
I reproduced the bug on a fresh global install in a docker container:
Generation of service with properties is ok.
If I globally install latest sequelize, re-generation of the service produces the invalid model content.
If I manually install sequelize 3.34.0 in the global installation of @feathers-plus/generator-feathers-plus, everything is ok.
Maybe sequelize 3.34.0 should be added to the dependencies of the generator package ?

**Comment by eddyystop** [comment]
@j2L4e I believe you use sequelize. If so do you want to reply to this?

**Comment by eddyystop** [comment]
cli+ was not written to be used locally. This is something we'll consider adding.
