### ISSUE TITLE
No knex support? Surprized

### ISSUE THREAD

**Issue by outluch** [feathers-plus/generator-feathers-plus#163]
Is it in roadmap or something?

**Comment by outluch** [comment]
Seems like not finished?

**Comment by eddyystop** [comment]
I could not find anyone willing to write a translator from json-schema to knex model, and then debug the code generated for knex.

**Comment by eddyystop** [comment]
The JSON-schema definition for the service fields is translated to the model used by Mongoose, Sequelize, etc. That has to be done for Knex as well.

https://github.com/feathers-plus/cli-generator-example/blob/master/js-sequelize-services/src/services/users/users.schema.js
to
https://github.com/feathers-plus/cli-generator-example/blob/master/js-sequelize-services/src/services/users/users.sequelize.js

**Comment by csotiriou** [comment]
Sequelize is an ORM.

Knex is not an ORM, it's an advanced database connector and query constructor.

BookshelfJS and Objection.JS are "ORM-like libraries" built on knex, but they are still not complete ORMs - they are more advanced query constructors as well. In Knex and its children libraries you don't define your schema - you can only write instructions as to how to create a table.

However, ObjectionJS is an extremely handy library - and in many cases it works way better than Sequelize. It has JSON Schema support in its models and I believe it should be added.

For me, not having Objection support is a deal breaker - that's why I still use the plain feathers cli, and not the "plus" one.

**Comment by eddyystop** [comment]
No one was willing to step up and help with Knex or Objection support. People should be willing to help get what they want rather than just consuming over a man-year of free work and asking for more.

**Comment by csotiriou** [comment]
@eddyystop

I was just pointing out the fact that neither Objection nor knex have models because they are not actual ORMs - so their treatment should be different than the one in Sequelize (and simpler). You do not need to create models for Knex / Objection, which was what @outluch was also trying to say.

And I also mentioned the "deal breaker" part not just to press you or anyone else, but at least to indicate its importance - especially for people using the old variant of the cli which already has this option (so when feathers+ becomes the standard cli, it's as if you are silently removing a feature). 

So, I'm sorry if my comment came across as a "do it DOITNOWTF!" comment. This really wasn't my intention - the fact that we are using feathers alone means we really do appreciate your work.

In any case, thank you for your work in this. I have 2 jobs at the moment, so I don't know if I have the time to invest in this. When this situation ends, I will revisit feathers+ and try to add this feature.

At least I hope that my comment about the models not being needed in knex / Objection have contributed something.

**Comment by eddyystop** [comment]
I do regret my knee jerk response and apologize for it. It was a symphtom of the industry starting to realize the open source model has become unsupportable.

I use neither knex nor objective so implementing support if of no benefit to me. I don't have the time to learn the nuances of either to implement support.

No one interested in such support has volunteered help results in this situation.
