### ISSUE TITLE
changing from npm to yarn in an existing project

### ISSUE THREAD

**Issue by MohammedFaragallah** [feathers-plus/generator-feathers-plus#226]
when regenerating app `feathers-plus g app`
then change from npm to yarn in Which package manager are you using question
i think the generator should change pachage.json engines from npm to yarn to make it work not only in the feathers-gen-specs.json file

**Comment by eddyystop** [comment]
The generator requires no package.json exist when the first `generate app` is run and it creates one based on the answers to the prompts. package.json tends to only be added to thereafter because the generator cannot distinguish between what it generated and what the dev wrote.

After that a core design philosophy is not to try to "undo" things when a prompt answer is changed, just to generate the code for the new value of the prompt. The reasoning, backed by experience, is that trying to "undo" things is a lost cause in general, which tends to produce unacceptable results.

If you change the value of a prompt, you are responsible for correctly "undoing" and residual code.

**Comment by MohammedFaragallah** [comment]
great insight Thanks @eddyystop
